spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/nttdataproject
          jwk-set-uri: http://localhost:8180/realms/nttdataproject/protocol/openid-connect/certs